// Do not edit. This file is machine generated by the Resource DLL Wizard.

library iRadio;

{$R *.RES}
{ITE} {LCID:00000804:00000409} {}
{ITE} {DFMFileType} {UnitAboutBox.dfm}
{ITE} {DFMFileType} {UnitDataModuleSignal.dfm}
{ITE} {DFMFileType} {UnitDialogUserInfo.dfm}
{ITE} {DFMFileType} {UnitFormCall.dfm}
{ITE} {DFMFileType} {UnitFormMain.dfm}
{ITE} {RCFileType} {iRadio_DRC.rc}

{$R 'UnitAboutBox.dfm' AboutBox:TForm}
{$R 'UnitDataModuleSignal.dfm' DataModuleSignal:TDataModule}
{$R 'UnitDialogUserInfo.dfm' DialogUserInfo:TForm}
{$R 'UnitFormCall.dfm' FormCall:TForm}
{$R 'UnitFormMain.dfm' FormMain:TForm}
{$R 'iRadio_DRC.res' 'iRadio_DRC.rc'}

{$E ENU}

begin
end.